import React from 'react';

interface MenuScreenProps {
  onNewGame: () => void;
  onLoadGame: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onContinue: () => void;
  canContinue: boolean;
  onGoToSettings: () => void;
}

const MenuScreen: React.FC<MenuScreenProps> = ({ onNewGame, onLoadGame, onContinue, canContinue, onGoToSettings }) => {
  return (
    <div className="flex flex-col items-center justify-center h-screen w-screen bg-slate-900 text-slate-100">
      <div className="text-center bg-slate-800/50 p-10 rounded-xl border border-slate-700 shadow-2xl backdrop-blur-sm">
        <h1 className="text-6xl font-bold text-cyan-400 mb-2" style={{ textShadow: '0 0 10px #22d3ee' }}>
          Gemini RPG
        </h1>
        <p className="text-slate-400 mb-8">An adventure generated by AI</p>
        <div className="flex flex-col gap-4 w-64 mx-auto">
          {canContinue && (
             <button
                onClick={onContinue}
                className="w-full bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-3 px-4 rounded-lg text-xl transition-all duration-300 transform hover:scale-105 shadow-lg"
              >
                Continue
              </button>
          )}
          <button
            onClick={onNewGame}
            className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-4 rounded-lg text-xl transition-all duration-300 transform hover:scale-105 shadow-lg"
          >
            New Game
          </button>
          <label className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-lg text-xl transition-all duration-300 transform hover:scale-105 shadow-lg text-center cursor-pointer">
            Load Game
            <input type="file" accept=".json" onChange={onLoadGame} className="hidden" />
          </label>
           <button
            onClick={onGoToSettings}
            className="w-full bg-slate-600 hover:bg-slate-700 text-white font-bold py-3 px-4 rounded-lg text-xl transition-all duration-300 transform hover:scale-105 shadow-lg"
          >
            Settings
          </button>
        </div>
      </div>
    </div>
  );
};

export default MenuScreen;